# Jekyll config

title: Meimei Lu
email: meimeilu@gwmail.gwu.edu
description: >-
  Meimei Lu, a Graphic Design BFA Candidate at GWU
url: "https://meimei.lu"

# Build settings
theme: minima
plugins:
  - jekyll-sitemap

exclude:
  - assets/og-img/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - convert-img.sh
  - CNAME

collections:
  works:
    output: true

permalink: pretty