# Jekyll config

title: Meimei Lu
email: hello@meimei.lu
fmail: t
description: UI/UX Designer in San Diego, CA – Portfolio of Meimei Lu.
url: "https://meimei.lu"

# Build settings
plugins:
  - jekyll-sitemap

exclude:
  - assets/og-img/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - convert-img.sh
  - CNAME
  - vendor

sass:
  style: normal;

collections:
  work:
    output: true

permalink: pretty

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 65
  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/"]
  # Whether to search in nested directories or not
  nested: true
  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  # File extensions for animated gif files 
  gifs: [".gif"]
  # Set to true to always regenerate existing webp files
  regenerate: false
  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil
  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []
  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################