# Jekyll config

title: Meimei Lu
email: hello@meimei.lu
fmail: t
description: UI/UX Designer in San Diego, CA – Portfolio of Meimei Lu.
url: "https://meimei.lu"

# Build settings
plugins:
  - jekyll-sitemap

exclude:
  - assets/og-img/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - convert-img.sh
  - CNAME
  - vendor

sass:
  style: normal;

collections:
  work:
    output: true

permalink: pretty
